routes/web.php
<?php
date_default_timezone_set('Asia/Kolkata');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
//     //return view('auth/login');

// });

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('process-notification','SopCompliance\NotificationController@processNotification')->name('process-notification');

    Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('permissions','PermissionController');
    Route::resource('division','DivisionController');
    Route::resource('department','DepartmentController');
    /* accessories_logic_input_sheets_upload_utility path */
    Route::resource('accessories-utility','AccessoriesUtilityController');

    /* Sop compliance Routes*/
    Route::get('sop','SopCompliance\SopDashboardController@index')->name('sopDashboard');
    Route::get('sop/{qus_id}', 'SopCompliance\SopDashboardController@show')->name('sopDetails');
    Route::get('assignedstore/{process_id}','SopCompliance\FormController@storeAssignedToProcess')->name('assignedstore');
    Route::get('submittedQuestions','SopCompliance\FormController@submittedQuestions')->name('submittedQuestions');
    Route::match(array('GET', 'POST'),'process-report','SopCompliance\Report\ProcessReportController@index');

    Route::resource('questions','SopCompliance\FormQuestionController');
    Route::resource('forms','SopCompliance\FormController');
    Route::get('shortquestion/{form_id}','SopCompliance\FormQuestionController@shortquestion')->name('shortquestion');
    Route::post('process_status','SopCompliance\FormController@process_status')->name('process_status');
    Route::match(array('GET', 'POST'),'create_question','SopCompliance\FormController@submitQuestion')->name('create_question');
    Route::post('questionFieldMapping','SopCompliance\FormController@questionFieldMapping')->name('questionFieldMapping');
    /***edit Question Routes***/
     Route::get('question/{id}/edit','SopCompliance\FormQuestionController@edit')->name('questionEdit');
    //Route::resource('form_question_mapping','SopCompliance\FormQuestionMappingController');
    //GRC Routes
    Route::group(['prefix' => 'grc', 'as' => 'grc.'], function () {
        Route::get('/','Grc\GrcController@index')->name('index');
        Route::get('import', 'Grc\GrcController@import')->name('import');
        Route::get('import/template', 'Grc\GrcController@importTemplate')->name('import.template');
        Route::post('import/save', 'Grc\GrcController@importSave')->name('import.save');
    });

    //PO Routes
    Route::group(['prefix'=> 'po', 'as'=>'po.'],function(){
        Route::get('/','Po\PoController@index')->name('index');
        Route::get('import/template', 'Po\PoController@importTemplate')->name('import.template');
        Route::get('import', 'Po\PoController@import')->name('import');
        Route::post('/import-save', 'Po\PoController@importSave')->name('import.save');
    });

    //PR Plan Routes
    Route::group(['prefix'=> 'pr-plan', 'as'=>'pr-plan.'],function(){
        Route::get('maj-cat','PrPlan\PrPlanController@majCat')->name('maj-cat');
        Route::get('maj-cat/import','PrPlan\PrPlanController@majCatImport')->name('maj-cat.import');

        Route::get('maj-cat-seg','PrPlan\PrPlanController@majCatSeg')->name('maj-cat-seg');
        Route::get('maj-cat-seg/import','PrPlan\PrPlanController@majCatSegImport')->name('maj-cat-seg.import');

        Route::get('maj-cat-seg-mvgr','PrPlan\PrPlanController@majCatSegMvgr')->name('maj-cat-seg-mvgr');
        Route::get('maj-cat-seg-mvgr/import','PrPlan\PrPlanController@majCatSegMvgrImport')->name('maj-cat-seg-mvgr.import');

        Route::get('reference-article','PrPlan\PrPlanController@referenceArticle')->name('reference-article');
        Route::get('reference-article/import','PrPlan\PrPlanController@referenceArticleImport')->name('reference-article.import');

        Route::get('options-article','PrPlan\PrPlanController@optionsArticle')->name('options-article');
        Route::get('options-article/import','PrPlan\PrPlanController@optionsArticleImport')->name('options-article.import');

        Route::get('auto-pr','PrPlan\PrPlanController@autoPr')->name('auto-pr');
        Route::get('auto-pr/import','PrPlan\PrPlanController@autoPrImport')->name('auto-pr.import');
    });
    // OTB Plan Routes
    Route::group(['prefix'=> 'otb-plan', 'as'=>'otb-plan.'],function(){
        Route::get('maj-cat','OtbPlan\OtbPlanController@majCat')->name('maj-cat');
        Route::get('maj-cat/import','OtbPlan\OtbPlanController@majCatImport')->name('maj-cat.import');

        Route::get('maj-cat-seg','OtbPlan\OtbPlanController@majCatSeg')->name('maj-cat-seg');
        Route::get('maj-cat-seg/import','OtbPlan\OtbPlanController@majCatSegImport')->name('maj-cat-seg.import');

        Route::get('maj-cat-seg-mvgr','OtbPlan\OtbPlanController@majCatSegMvgr')->name('maj-cat-seg-mvgr');
        Route::get('maj-cat-seg-mvgr/import','OtbPlan\OtbPlanController@majCatSegMvgrImport')->name('maj-cat-seg-mvgr.import');

        Route::get('reference-article','OtbPlan\OtbPlanController@referenceArticle')->name('reference-article');
        Route::get('reference-article/import','OtbPlan\OtbPlanController@referenceArticleImport')->name('reference-article.import');

        Route::get('options-article','OtbPlan\OtbPlanController@optionsArticle')->name('options-article');
        Route::get('options-article/import','OtbPlan\OtbPlanController@optionsArticleImport')->name('options-article.import');
    });

    //Zonning
    Route::view('zonning', 'zonning.zonning');
});

app/Http/Controllers/Api/SopCompliance/FormController.php
<?php
namespace App\Http\Controllers\Api\SopCompliance;

use Master\Models\StoresModel;
use App\Model\SopCompliance\Form;
use App\Model\SopCompliance\FormQuestion;
use App\Model\SopCompliance\FormField;
use App\Model\SopCompliance\FormFieldValue;
use App\Model\SopCompliance\SurveyFormSubmission;
use App\Model\SopCompliance\SurveyFormSubmissionValue;
use App\Model\SopCompliance\FormRoleMapping;

use App\Model\SopCompliance\FormQuestionTimeMapping;
use App\Model\SopCompliance\FormQuestionTimeTaken;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Validator;
use App\User;
use Illuminate\Support\Facades\Mail;
use App\Helpers\NotificationHelper;
use Spatie\Permission\Models\Role;
use Config;
use Carbon\Carbon;
use File;

class FormController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            'latitude' => 'required',
            'longitude' => 'required'
        ]);
        if ($validator->fails()) {
            $this->return = array('status'=>0, 'message'=>$validator->errors()->first());
            $status = 200;
        } else{
        $user=Auth::User();

        $user_id=Auth::User()->id;
        $store_id=Auth::User()->store_id;

        $role_id = $user->roles->first()->id;

        if($role_id){

            $formIdData = FormRoleMapping::where('role_id', $role_id)->get()->pluck('form_id');

            if($formIdData->toArray()){
                $formIds = $formIdData->toArray();

                $sopFormData = Form::with('user')->whereIn('id', $formIds)->where('status', '1')->get();

                foreach ($sopFormData as $sopFormDatakey => $sopFormDatavalue) {
                    # code...
                    $sopFormDatavalue->form_name=strtoupper($sopFormDatavalue->form_name);
                    $sopFormDatavalue->form_label=strtoupper($sopFormDatavalue->form_label);
                    $sopFormDatavalue->store_id=$user->store_id;

                    //echo $user->store_id; die;
                    if($user->store_id && $user->store_id!=null){
                        $storeData =  DB::select("SELECT s.st_code  FROM stores AS s where s.id = '".$user->store_id."'");
                        if(!empty($storeData)){
                            $sopFormDatavalue->store_code=$storeData[0]->st_code;
                        }else{
                            $sopFormDatavalue->store_code='';
                        }
                    }else{
                        $sopFormDatavalue->store_code='';
                    }

                    $questioncount = FormQuestion::join('sop_form_fields', function ($join) {
                                        $join->on('sop_form_questions.id', '=', 'sop_form_fields.form_question_id')
                                            ->where('sop_form_fields.field_type','=','radio')
                                            ->where('sop_form_fields.parent_id','=','0');
                                    })->join('sop_form_field_values', function ($join) {
                                        $join->on('sop_form_fields.id', '=', 'sop_form_field_values.form_field_id')
                                            ->where('sop_form_field_values.is_scorable','=','1');
                                    })
                                    ->where('sop_form_questions.form_id', $sopFormDatavalue->id)->where('sop_form_questions.parent_id', 0)->count();

                    // $questioncount = FormQuestion::where('form_id', $sopFormDatavalue->id)->where('parent_id', 0)->count();
                    $availed_score =0;
                    $percentage = 0;
                    $yesCount= 0;


                    $questionnumberofyesCount = DB::select("SELECT COUNT(*) AS count  FROM sop_form_questions AS q
                              JOIN sop_form_fields AS f ON f.form_question_id=q.id AND f.field_type='radio' AND f.parent_id='0' AND q.parent_id='0'
                              JOIN sop_form_field_values AS v ON v.form_field_id=f.id AND (v.is_scorable='1')
                              JOIN sop_survey_form_submission AS fs ON fs.question_id=q.id AND fs.form_id=q.form_id
                              JOIN sop_survey_form_submission_value AS sv ON sv.field_id=f.id AND sv.field_value_id=v.id
                              WHERE q.form_id = '".$sopFormDatavalue->id."' AND fs.store_id = '".$store_id."' AND fs.date = '".date('Y-m-d')."'
                              GROUP BY q.id");

                             // dd($questionnumberofyesCount);
                    //echo '<pre>'; print_r($questionnumberofyesCount);
                    //print_r($questionnumberofyesCount[0]->count);
                    if(!empty($questionnumberofyesCount)){
                        foreach ($questionnumberofyesCount as $questionnumberofyesCountkey => $questionnumberofyesCountvalue) {
                            # code...
                            $yesCount += $questionnumberofyesCountvalue->count;
                        }
                        //$yesCount = $questionnumberofyesCount[0]->count;
                        $availed_score = $yesCount;
                    }else{
                        $yesCount = 0;
                        $availed_score = 0;
                    }
                    //$yesCount= $questionnumberofyesCount ? $questionnumberofyesCount[0]->count :'0';

                    //$availed_score = $questioncount - $yesCount;
                    $percentage = $questioncount>0 ? round((($availed_score/$questioncount)*100),2) :'0' ;

                    $sopFormData[$sopFormDatakey]->availed_score = $availed_score.'.00';
                    $sopFormData[$sopFormDatakey]->percentage = $percentage.'%';
                    if(!empty($questioncount) && $questioncount!=''){
                        $sopFormData[$sopFormDatakey]->total_score = $questioncount.'.00';
                    }else{
                        $sopFormData[$sopFormDatakey]->total_score = '00.00';
                    }
                     $currDate = date('Y-m-d');
                 
                    $perFormQuestionCount = FormQuestion::where('form_id', $sopFormDatavalue->id)->where('parent_id', 0)->where('status', '1')->count();
                 
                   
                    $perFormQuestionSubmittedCount = SurveyFormSubmission::where(array('form_id'=>$sopFormDatavalue->id,'date'=>$currDate))->count();
                   // pr($perFormQuestionCount);
                    
                 //   prd($perFormQuestionSubmittedCount);
                    // 1=>'Completed', 2=>'Partial Completed', 3=>'Not Completed'
                    if($perFormQuestionCount == $perFormQuestionSubmittedCount){
                        $sopFormData[$sopFormDatakey]->form_status = 1; // Completed

                    }else if($perFormQuestionCount > $perFormQuestionSubmittedCount){
                        $sopFormData[$sopFormDatakey]->form_status = 2; // Partial Completed
                    }else{
                        $sopFormData[$sopFormDatakey]->form_status = 3; // Not Completed
                    }
                    //$sopFormData[$sopFormDatakey]->form_status = 1;
                    $sopFormData[$sopFormDatakey]->server_date = date('d-m-Y');
                }

                if($sopFormData) {
                    $this->return['message'] = 'SopCompliance Form Data';
                    $this->return['status'] = 1;
                    $this->return['jsonData'] = $sopFormData;
                    $status = 200;
                } else{
                     $this->return['message'] = 'No SopCompliance Form Data Found';
                     $this->return['status'] = 0;
                    $status = 200;
                }
            }else{
                $this->return['message'] = 'Form data not found.';
                $this->return['status'] = 0;
                $status = 200;
            }
        }else{
            $this->return['message'] = 'User role not found.';
            $this->return['status'] = 0;
            $status = 200;
        }
    }
        return response()->json($this->return, $status);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function show(Form $form)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function edit(Form $form)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Form $form)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Form  $form
     * @return \Illuminate\Http\Response
     */
    public function destroy(Form $form)
    {
        //
    }

    public function sop_form_data(Request $request)
    {
        //
        $validator = Validator::make($request->all(), [
            'form_id' => 'required',
            'store_id' => 'required',
            'latitude' => 'required',
            'longitude' => 'required',
        ]);

resources/views/sopcompliance/form/index.blade.php
@extends('layouts.app') 
@section('style')
<link href="{{ asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
@endsection
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
   <h1>
      Process List
   </h1>
   <ol class="breadcrumb">
      <li><a href="{{ route('home')}}"><i class="fa fa-home"></i>Home</a></li>
      <li><a href="{{ route('sopDashboard')}}">V2 Shop Compliance</a></li>
      <li class="active">Process List</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="container-fluid">
   <div class="card listcontainer">
   <div class="card-header">
      <div class="col-sm-12 list_filter_head">
         <div class="search_box">
            <!-- search form -->
            <form action="#" method="get" class="sidebar-form">
               <div class="input-group">
                  <input type="text" name="searchtxt" value="<?php echo isset($forms->searchtxt) ? $forms->searchtxt : ''; ?>" class="form-control search" placeholder="Search...">
                  <span class="input-group-btn">
                  <button type="submit" name="search" value="save" id="search-btn" class="btn btn-flat">
                  <i class="fa fa-search"></i>
                  </button>
                  </span>
               </div>
            </form>
         </div>
         {!! Form::open(array('url' => 'process-report','method'=>'POST')) !!}
           
             <div class="col-sm-3 " style="margin-top:10px;">
                <select class="form-control" name="process" required>
                  <option value="">Select Process</option>
                  @foreach($forms as $process)
                   <option value="{{$process->id}}">{{$process->form_label}}</option>
                  @endforeach
                </select>
             </div>
             <div class="col-sm-3 " style="margin-top:10px;" >
                 <div class="input-group">
                  <div class="input-group-prepend">
                     <span class="input-group-text">
                     <i class="far fa-calendar-alt"></i>
                     </span>
                  </div>
                  <input type="text" name="month_year" id="month_year" class="form-control dateinput form-control-2 to" placeholder="Select month and year" value="{{ \Carbon\Carbon::now()->format('m-Y') }}">
               </div>
               </div>
             <div class="col-sm-1">
              <button type="submit" class="btn btn-primary btn-submit">Export</button>
            </div>
           {!! Form::close() !!}
         <div class="userbtn d-flex">
            <div class="clearfix">
            
            <a href="javascript:void(0);" class="btn btn-primary createuser-btn pt-0 " onclick="processStatus('1');">
            Active
            </a>
            <a href="javascript:void(0);" class="btn btn-primary mx-10 createuser-btn pt-0" onclick="processStatus('0');">
            Inactive
            </a>
            <a href="{{route('forms.create')}}" class="btn btn-primary createuser-btn pt-0">
            <i class="fa fa-plus-circle"></i> Add Process
            </a>
            </div>
         </div>
      </div>
   </div>
   <!-- /.card-header -->
   <div class="card-body">
      @if ($message = Session::get('success'))
      <div class="message" form="alert">
         <div class="alert alert-success">
            <p>{{ $message }}</p>
         </div>
      </div>
      @endif
      <!-- <div class="container-fluid p-0 show-enteries-parent">
         <div class="col-md-6 p-0">
            <label class="show-enteries-text">
               Show enteries
               <select id="item-show-per-page-select" class="item-show-per-page-select-id">
                  <option value="10">10</option>
                  <option value="50">50</option>
                  <option value="150">150</option>
                  <option value="500">500</option>
               </select>
            </label>
         </div>
         <div class="col-md-6 p-0">
            <p class="showing-enteries-text text-right">Showing 1 to 10 of 57 entries</p>
         </div>
      </div> -->
      <div class="table_data">
         <table class="table table-stripd table-bordered Process">
            <thead>
               <tr>
                  <th>
                     <div class="icheck-primary my-0">
                        <input type="checkbox" name="SelectAll" id="SelectAll">
                        <label for="SelectAll" class="selectall"></label>
                     </div>
                  </th>
                  <th>Process Full Name</th>
                  <th>Process Short Name</th>
                  <th>Created On</th>
                  <th>Status</th>
                  <th>Action</th>	
               </tr>
            </thead>
            <tbody>
               {{ Form::open(array('method'=>'post','class'=> 'col-md-6','url' => '#', 'id'=>'process-form')) }} @php $i=1; @endphp @forelse ($forms as $key => $form)
               <tr>
                  @php $arr=array('1'=>'Audit','2'=>'Data Collection','3'=>'Assesment'); @endphp
                  <td align="left">
                     <div class="icheck-primary my-0">
                        <input type="checkbox" name="IndivualSelect" id="IndivualSelect{{ $i }}" class="IndivualSelect" value="{{$form->id}}">
                        <label for="IndivualSelect{{ $i }}"></label>
                  </td>
                  <td>{{ $form->form_name }}</td>
                  <td>{{ $form->form_label }}</td>
                  <td>{{ \Carbon\carbon::parse($form->created_at)->format('d-m-Y') }}</td>
                  <td>{{ !empty($form->status) ? 'Active' : 'Deactive' }}</td>
                  <td>
                  @can('form-edit')
                  <a class="btn btn-primary btn_dis" href="{{ route('forms.edit',$form->id) }}" data-toggle="tooltip" title="Edit!"><i class="fa fa-edit"></i></a> @endcan @can('form-delete') {!! Form::open(['method' => 'DELETE','route' => ['forms.destroy', $form->id],'style'=>'display:inline']) !!}
                  <!--button type="submit" class="btn btn-danger btn_dis delete_btn"><i class="fa fa-archive"></i></button-->
                  {!! Form::close() !!} @endcan
                  <a class="btn btn-primary btn_dis" href="{{ route('assignedstore',base64_encode($form->id)) }}" title="View"><i class="fa fa-eye"></i></a>
                  </td>
               </tr>
               @php $i++ @endphp
               @empty
               <tr>
               <td colspan="3">
               !! No Record Found !!
               </td>
               </tr>
               @endforelse
               {{ Form::close() }}
            </tbody>
         </table>
         </div>
      </div>
      <div class="col-md-12 text-right pagination">
         {!! $forms->render() !!}
      </div>
   </div>
</section>
@endsection

@section('custom-js')
<script src="{{ asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<script>
  $(document).ready(function() {
    $(document).on('click', 'label.selectall, input#SelectAll', function(){
        if($('input#SelectAll').is(":checked")){
            $('input.IndivualSelect').attr('checked', true);
        }else{
          $('input.IndivualSelect').attr('checked', false);
        }   
  });

});

jQuery(function() {
    jQuery('[data-check-pattern]').checkAll();
});

;(function($) {
    'use strict';
    
    $.fn.checkAll = function(options) {
        return this.each(function() {
            var mainCheckbox = $(this);
            var selector = mainCheckbox.attr('data-check-pattern');
            var onChangeHandler = function(e) {
                var $currentCheckbox = $(e.currentTarget);
                var $subCheckboxes;
                
                if ($currentCheckbox.is(mainCheckbox)) {
                    $subCheckboxes = $(selector);
                    $subCheckboxes.prop('checked', mainCheckbox.prop('checked'));
                } else if ($currentCheckbox.is(selector)) {
                    $subCheckboxes = $(selector);
                    mainCheckbox.prop('checked', $subCheckboxes.filter(':checked').length === $subCheckboxes.length);
                }
            };
            
            $(document).on('change', 'input[type="checkbox"]', onChangeHandler);
        });
    };
}(jQuery));

  // $(document).ready(function() {
   //  $(document).on('click', 'label.selectall, input#SelectAll', function(){
      //   if($('input#SelectAll').is(":checked")){
        //     $('input.IndivualSelect').attr('checked', true);
       //  }else{
      //     $('input.IndivualSelect').attr('checked', false);
      //   }
  // });
   
  // });
   
   function processStatus(status){
        var checkedVal = [];
        $("input:checkbox[name='IndivualSelect']:checked").each(function(){
         checkedVal.push($(this).val());
     });
        $.ajax({
            type: "POST",
            url: '{{ route('process_status')}}',
            data: {"_token": "{{ csrf_token() }}", data:checkedVal, status:status},
            success: function( msg ) {
             if(msg.status==1){
               location.reload(true);
             }
            }
        });
    }

    $(document).ready(function () {
       $('.to').datepicker({
           autoclose: true,
           minViewMode: 1,
           format: 'mm-yyyy',
           default: true
       })
       $('#month_year').on("change",function(){
           var monthYear = $(this).val();
           $("#process-report").attr("href", APP_URL+"/process-report?dt="+monthYear)
       });

   });
   
</script>
@endsection