routes/web.php
<?php
date_default_timezone_set('Asia/Kolkata');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
//     //return view('auth/login');

// });

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('process-notification','SopCompliance\NotificationController@processNotification')->name('process-notification');

    Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('permissions','PermissionController');
    Route::resource('division','DivisionController');
    Route::resource('department','DepartmentController');
    /* accessories_logic_input_sheets_upload_utility path */
    Route::resource('accessories-utility','AccessoriesUtilityController');

    /* Sop compliance Routes*/
    Route::get('sop','SopCompliance\SopDashboardController@index')->name('sopDashboard');
    Route::get('sop/{qus_id}', 'SopCompliance\SopDashboardController@show')->name('sopDetails');
    Route::get('assignedstore/{process_id}','SopCompliance\FormController@storeAssignedToProcess')->name('assignedstore');
    Route::get('submittedQuestions','SopCompliance\FormController@submittedQuestions')->name('submittedQuestions');
    Route::match(array('GET', 'POST'),'process-report','SopCompliance\Report\ProcessReportController@index');

    Route::resource('questions','SopCompliance\FormQuestionController');
    Route::resource('forms','SopCompliance\FormController');
    Route::get('shortquestion/{form_id}','SopCompliance\FormQuestionController@shortquestion')->name('shortquestion');
    Route::post('process_status','SopCompliance\FormController@process_status')->name('process_status');
    Route::match(array('GET', 'POST'),'create_question','SopCompliance\FormController@submitQuestion')->name('create_question');
    Route::post('questionFieldMapping','SopCompliance\FormController@questionFieldMapping')->name('questionFieldMapping');
    /***edit Question Routes***/
     Route::get('question/{id}/edit','SopCompliance\FormQuestionController@edit')->name('questionEdit');
    //Route::resource('form_question_mapping','SopCompliance\FormQuestionMappingController');
    //GRC Routes
    Route::group(['prefix' => 'grc', 'as' => 'grc.'], function () {
        Route::get('/','Grc\GrcController@index')->name('index');
        Route::get('import', 'Grc\GrcController@import')->name('import');
        Route::get('import/template', 'Grc\GrcController@importTemplate')->name('import.template');
        Route::post('import/save', 'Grc\GrcController@importSave')->name('import.save');
    });

    //PO Routes
    Route::group(['prefix'=> 'po', 'as'=>'po.'],function(){
        Route::get('/','Po\PoController@index')->name('index');
        Route::get('import/template', 'Po\PoController@importTemplate')->name('import.template');
        Route::get('import', 'Po\PoController@import')->name('import');
        Route::post('/import-save', 'Po\PoController@importSave')->name('import.save');
    });

    //PR Plan Routes
    Route::group(['prefix'=> 'pr-plan', 'as'=>'pr-plan.'],function(){
        Route::get('maj-cat','PrPlan\PrPlanController@majCat')->name('maj-cat');
        Route::get('maj-cat/import','PrPlan\PrPlanController@majCatImport')->name('maj-cat.import');

        Route::get('maj-cat-seg','PrPlan\PrPlanController@majCatSeg')->name('maj-cat-seg');
        Route::get('maj-cat-seg/import','PrPlan\PrPlanController@majCatSegImport')->name('maj-cat-seg.import');

        Route::get('maj-cat-seg-mvgr','PrPlan\PrPlanController@majCatSegMvgr')->name('maj-cat-seg-mvgr');
        Route::get('maj-cat-seg-mvgr/import','PrPlan\PrPlanController@majCatSegMvgrImport')->name('maj-cat-seg-mvgr.import');

        Route::get('reference-article','PrPlan\PrPlanController@referenceArticle')->name('reference-article');
        Route::get('reference-article/import','PrPlan\PrPlanController@referenceArticleImport')->name('reference-article.import');

        Route::get('options-article','PrPlan\PrPlanController@optionsArticle')->name('options-article');
        Route::get('options-article/import','PrPlan\PrPlanController@optionsArticleImport')->name('options-article.import');

        Route::get('auto-pr','PrPlan\PrPlanController@autoPr')->name('auto-pr');
        Route::get('auto-pr/import','PrPlan\PrPlanController@autoPrImport')->name('auto-pr.import');
    });
    // OTB Plan Routes
    Route::group(['prefix'=> 'otb-plan', 'as'=>'otb-plan.'],function(){
        Route::get('maj-cat','OtbPlan\OtbPlanController@majCat')->name('maj-cat');
        Route::get('maj-cat/import','OtbPlan\OtbPlanController@majCatImport')->name('maj-cat.import');

        Route::get('maj-cat-seg','OtbPlan\OtbPlanController@majCatSeg')->name('maj-cat-seg');
        Route::get('maj-cat-seg/import','OtbPlan\OtbPlanController@majCatSegImport')->name('maj-cat-seg.import');

        Route::get('maj-cat-seg-mvgr','OtbPlan\OtbPlanController@majCatSegMvgr')->name('maj-cat-seg-mvgr');
        Route::get('maj-cat-seg-mvgr/import','OtbPlan\OtbPlanController@majCatSegMvgrImport')->name('maj-cat-seg-mvgr.import');

        Route::get('reference-article','OtbPlan\OtbPlanController@referenceArticle')->name('reference-article');
        Route::get('reference-article/import','OtbPlan\OtbPlanController@referenceArticleImport')->name('reference-article.import');

        Route::get('options-article','OtbPlan\OtbPlanController@optionsArticle')->name('options-article');
        Route::get('options-article/import','OtbPlan\OtbPlanController@optionsArticleImport')->name('options-article.import');
    });

    //Zonning
    Route::view('zonning', 'zonning.zonning');
});

app/Http/Controllers/PrPlan/PrPlanController.php
<?php

namespace App\Http\Controllers\PrPlan;

use App\Http\Controllers\Controller;
use App\Model\Grc\Grc;
use Illuminate\Http\Request;
use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;
use App\Imports\GrcImport;
use App\Exports\Export;

class PrPlanController extends Controller
{
    public function majCat()
    {
        return view('prplan.majcat.index');
    }

    public function majCatImport(Request $request)
    {
        return view('prplan.majcat.import');
    }

    public function majCatSeg()
    {
        return view('prplan.majcatseg.index');
    }

    public function majCatSegImport(Request $request)
    {
        return view('prplan.majcatseg.import');
    }

    public function majCatSegMvgr()
    {
        return view('prplan.majcatsegmvgr.index');
    }

    public function majCatSegMvgrImport(Request $request)
    {
        return view('prplan.majcatsegmvgr.import');
    }

    public function referenceArticle()
    {
        return view('prplan.referencearticle.index');
    }

    public function referenceArticleImport(Request $request)
    {
        return view('prplan.referencearticle.import');
    }

    public function optionsArticle()
    {
        return view('prplan.optionsarticle.index');
    }

    public function optionsArticleImport(Request $request)
    {
        return view('prplan.optionsarticle.import');
    }

    public function autoPr()
    {
        return view('prplan.autopr.index');
    }

    public function autoPrImport(Request $request)
    {
        return view('prplan.autopr.import');
    }

}

resources/views/prplan/optionsarticle/import.blade.php
@extends('layouts.app')


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Import Options Article
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
        <li><a href="#">PR Plan</a></li>
        <li>Options Article</li>
        <li class="active"> Import Options Article</li>
    </ol>
</section>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- SELECT2 EXAMPLE -->
        <div class="card card-default">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="form_container">
                    <form class="md-form" action="" id="importform" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="custom-file file-field">
                            <p class="file-box-main-heading">Upload Option Article Detail</p>
                            <div class="file-field-inner">
                                <div class="browse-and-drag-drop-parent">
                                    <div class="upload-img-container">
                                        <img src="{{url('dist/img/upload-icon.png')}}" class="img-responsive">
                                    </div>
                                    <label class="drag-drop-text">Drag and Drop file here</label>
                                    <p class="or-text">or</p>
                                    <input type="file" name="file" id="custom-browse-btn">
                                    <label class="browse-file-lbl"> Browse file</label>
                                    <p class="file-format-text">(File format .xlsx)</p>
                                </div>
                                <span id="file-name"></span>
                                @error('file')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                                <div class="form-group pt-2 text-center">
                                    <input type="submit" class="btn btn-primary btn-submit" name="submit" id="submit" value="Submit">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom-js')
<script src="{{ asset('js/importjs.js') }}"></script>
@endsection

resources/views/prplan/optionsarticle/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
            Options Article
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-home"></i>Home</a></li>
        <li><a href="#">PR Plan</a></li>
        <li class="active">Options Article</li>
    </ol>
</section>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="col-sm-12 list_filter_head">
                    <div class="search_box">
                        <!-- search form -->
                        <form action="#" method="get" class="sidebar-form">
                            <div class="input-group">
                                <input type="text" name="search" class="form-control search" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="userbtn">
                       <a href="#" class="btn btn-sm btn-primary createuser-btn mx-10"><i class="fa fa-download"></i>Download Template</a>                        
                        <a href="{{ route('pr-plan.options-article.import') }}" class="btn btn-sm btn-primary createuser-btn"><i class="fa fa-upload"></i>Upload</a>                                 

                    </div>
                </div>
            </div>
            <!-- /.card-header -->

            <div class="card-body">


                  @if ($message = Session::get('success'))
         <div class="message" role="alert">
            <div class="alert alert-success alert-dismissible">
               <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            </div>
         </div>
         @endif
         <div class="container-fluid p-0 show-enteries-parent">
            <div class="col-md-6 p-0"><label class="show-enteries-text">Show enteries
               {!! Form::select('per_page', [10=>10,50=>50,150=>150,500=>500], app('request')->input('perpage'), ['class'=>'item-per-page','id'=>'item-show-per-page']) !!}
               </label>
            </div>
            <div class="col-md-6 p-0">
               <p class="showing-enteries-text text-right">Showing 1 to 10 of 57 entries</p>
            </div>
         </div>
              
                <div class="table_data">
                    <table class="table table-bordered table-striped">
                      <thead>
                            <tr>
                                <th>Options Article</th>
                                <th>Month Range</th>
                                <th>Uploaded Date</th>
                                <th>Modified date</th>
                                <th>Actions</th>                               
                            </tr>
                        </thead> 
                        <tbody>
                               <tr>
                                <td><p class="file-name-inside-table green-color">file-name.csv</p></td>
                                <td>Feb to Mar</td>
                                <td>20-02-2020</td>
                                <td>22-02-2020</td>
                                <td><a class="btn btn-primary btn_dis" title=""  data-toggle="tooltip" data-original-title="Download"><i class="fa fa-download"></i></a>

                                </td>
                               
                            </tr>

                        </tbody>
                    </table>
                    <div class="card-footer">
                    <div class="col-md-12 text-right pagination">
                    </div>
                </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
</section>

@endsection