routes/web.php
<?php
date_default_timezone_set('Asia/Kolkata');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     //return view('welcome');
//     //return view('auth/login');

// });

    Auth::routes();

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('process-notification','SopCompliance\NotificationController@processNotification')->name('process-notification');

    Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('permissions','PermissionController');
    Route::resource('division','DivisionController');
    Route::resource('department','DepartmentController');
    /* accessories_logic_input_sheets_upload_utility path */
    Route::resource('accessories-utility','AccessoriesUtilityController');

    /* Sop compliance Routes*/
    Route::get('sop','SopCompliance\SopDashboardController@index')->name('sopDashboard');
    Route::get('sop/{qus_id}', 'SopCompliance\SopDashboardController@show')->name('sopDetails');
    Route::get('assignedstore/{process_id}','SopCompliance\FormController@storeAssignedToProcess')->name('assignedstore');
    Route::get('submittedQuestions','SopCompliance\FormController@submittedQuestions')->name('submittedQuestions');
    Route::match(array('GET', 'POST'),'process-report','SopCompliance\Report\ProcessReportController@index');

    Route::resource('questions','SopCompliance\FormQuestionController');
    Route::resource('forms','SopCompliance\FormController');
    Route::get('shortquestion/{form_id}','SopCompliance\FormQuestionController@shortquestion')->name('shortquestion');
    Route::post('process_status','SopCompliance\FormController@process_status')->name('process_status');
    Route::match(array('GET', 'POST'),'create_question','SopCompliance\FormController@submitQuestion')->name('create_question');
    Route::post('questionFieldMapping','SopCompliance\FormController@questionFieldMapping')->name('questionFieldMapping');
    /***edit Question Routes***/
     Route::get('question/{id}/edit','SopCompliance\FormQuestionController@edit')->name('questionEdit');
    //Route::resource('form_question_mapping','SopCompliance\FormQuestionMappingController');
    //GRC Routes
    Route::group(['prefix' => 'grc', 'as' => 'grc.'], function () {
        Route::get('/','Grc\GrcController@index')->name('index');
        Route::get('import', 'Grc\GrcController@import')->name('import');
        Route::get('import/template', 'Grc\GrcController@importTemplate')->name('import.template');
        Route::post('import/save', 'Grc\GrcController@importSave')->name('import.save');
    });

    //PO Routes
    Route::group(['prefix'=> 'po', 'as'=>'po.'],function(){
        Route::get('/','Po\PoController@index')->name('index');
        Route::get('import/template', 'Po\PoController@importTemplate')->name('import.template');
        Route::get('import', 'Po\PoController@import')->name('import');
        Route::post('/import-save', 'Po\PoController@importSave')->name('import.save');
    });

    //PR Plan Routes
    Route::group(['prefix'=> 'pr-plan', 'as'=>'pr-plan.'],function(){
        Route::get('maj-cat','PrPlan\PrPlanController@majCat')->name('maj-cat');
        Route::get('maj-cat/import','PrPlan\PrPlanController@majCatImport')->name('maj-cat.import');

        Route::get('maj-cat-seg','PrPlan\PrPlanController@majCatSeg')->name('maj-cat-seg');
        Route::get('maj-cat-seg/import','PrPlan\PrPlanController@majCatSegImport')->name('maj-cat-seg.import');

        Route::get('maj-cat-seg-mvgr','PrPlan\PrPlanController@majCatSegMvgr')->name('maj-cat-seg-mvgr');
        Route::get('maj-cat-seg-mvgr/import','PrPlan\PrPlanController@majCatSegMvgrImport')->name('maj-cat-seg-mvgr.import');

        Route::get('reference-article','PrPlan\PrPlanController@referenceArticle')->name('reference-article');
        Route::get('reference-article/import','PrPlan\PrPlanController@referenceArticleImport')->name('reference-article.import');

        Route::get('options-article','PrPlan\PrPlanController@optionsArticle')->name('options-article');
        Route::get('options-article/import','PrPlan\PrPlanController@optionsArticleImport')->name('options-article.import');

        Route::get('auto-pr','PrPlan\PrPlanController@autoPr')->name('auto-pr');
        Route::get('auto-pr/import','PrPlan\PrPlanController@autoPrImport')->name('auto-pr.import');
    });
    // OTB Plan Routes
    Route::group(['prefix'=> 'otb-plan', 'as'=>'otb-plan.'],function(){
        Route::get('maj-cat','OtbPlan\OtbPlanController@majCat')->name('maj-cat');
        Route::get('maj-cat/import','OtbPlan\OtbPlanController@majCatImport')->name('maj-cat.import');

        Route::get('maj-cat-seg','OtbPlan\OtbPlanController@majCatSeg')->name('maj-cat-seg');
        Route::get('maj-cat-seg/import','OtbPlan\OtbPlanController@majCatSegImport')->name('maj-cat-seg.import');

        Route::get('maj-cat-seg-mvgr','OtbPlan\OtbPlanController@majCatSegMvgr')->name('maj-cat-seg-mvgr');
        Route::get('maj-cat-seg-mvgr/import','OtbPlan\OtbPlanController@majCatSegMvgrImport')->name('maj-cat-seg-mvgr.import');

        Route::get('reference-article','OtbPlan\OtbPlanController@referenceArticle')->name('reference-article');
        Route::get('reference-article/import','OtbPlan\OtbPlanController@referenceArticleImport')->name('reference-article.import');

        Route::get('options-article','OtbPlan\OtbPlanController@optionsArticle')->name('options-article');
        Route::get('options-article/import','OtbPlan\OtbPlanController@optionsArticleImport')->name('options-article.import');
    });

    //Zonning
    Route::view('zonning', 'zonning.zonning');
});

app/Http/Controllers/DivisionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Model\DivisionModel;
use App\User;
use Spatie\Permission\Models\Role;
use DB;

class DivisionController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $data = new DivisionModel();
        $fields = $data->getTableColumns();
        if (isset($request->search) && isset($request->searchtxt)) {
            foreach ($fields as $value) {
                if ($value == 'id' or
                        $value == 'created_at'
                        or $value == 'updated_at' or $value == 'st_status') {
                    continue;
                }
                $data = $data->orWhere($value, 'like', '%' . $request->searchtxt . '%');
            }
            $data = $data->orderBy('id', 'DESC')->paginate(15);
        } else {
            $data = $data->orderBy('id', 'DESC')->paginate(15);
        }
        $data->searchtxt = $request->searchtxt ? $request->searchtxt : '';


        return view('division.index', compact('data'))->with('i', ($request->input('page', 1) - 1) * 5);
    }

    public function edit($id) {
        $DataObj = DivisionModel::where(['id' => $id])->first();

        return view('division.create', ['DataObj' => $DataObj, 'id' => $id]);
    }

    public function create() {
        $DivisionObj = new DivisionModel();
        return view('division.create', ['DivisionObj' => $DivisionObj]);
    }

    public function show(Request $request) {
        echo "hi..show...";
        die();
    }

    public function store(Request $request) {

        $DataObj = new DivisionModel();
        
         $messages = array(
            'required' => 'This field is required.',
        );
        $validator = Validator::make($request->all(), [
                    'div_name' => 'required|string|max:50',
//                    'div_code' => 'required|string|max:90',
//                    'div_desc' => 'required|string|max:200',
                    'div_status' => 'required',
        ],$messages);

        if ($validator->fails()) {

            return view('division.create', ['errors' => $validator->errors(), 'DataObj' => $request]);
        }
        $input = $request->all();

        $DataObj->create($input);
        return redirect()->route('division.index')
                        ->with('success', 'Division created successfully');
    }

    public function update(Request $request) {

        $validator = Validator::make($request->all(), [
                    'div_name' => 'required|string|max:50',
//                    'div_code' => 'required|string|max:90',
//                    'div_status' => 'required',
                    'id' => 'required'
        ]);

        if ($validator->fails()) {
            return view('division.create', ['errors' => $validator->errors(), 'DataObj' => $request]);
        }

        if (isset($request->id)) {
            $DataObj = DivisionModel::find($request->id);
            $DataObj->update($request->all());
            return redirect()->route('division.index')
                            ->with('success', 'Division Updated successfully');
        } else {
            return "Record not found";
        }
    }

    public function destroy($id) {

        DivisionModel::find($id)->delete();

        return redirect()->route('division.index')
                        ->with('success', 'Division deleted successfully');
    }

}

resources/views/division/create.blade.php
@extends('layouts.app')


@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Create Division
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Home</a></li>
        <li ><a href="{{ route('division.index') }}">Divisions</a></li>
        <li class="active">Create Division</li>
    </ol>
</section>
<!-- /.content-header -->
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- SELECT2 EXAMPLE -->
        <div class="card card-default">
            <!-- /.card-header -->
            <div class="card-body">
                <div class="form_container">

                  
                    <form action="<?php if (isset($id)) { ?>{{ route('division.update',$id) }} <?php } else { ?>{{ route('division.store') }}<?php } ?>" method="POST">
                        @csrf
                        <?php if (isset($id)) { ?>
                            @method('PUT')
                        <?php } ?>
                        <input type="hidden" name='id' name='id' value="<?php if (isset($id)) {
                            echo $id;
                        } ?>" />
                        <div class="row">
                            <div class="clearfix">
                                <div class="col-md-6 right_pdng">
                                    <div class="form-group">
                                        <label >Name:</label>
                                        <input  type="text" name="div_name" id="div_name" value="<?php if (isset($DataObj->div_name)) {
                            echo $DataObj->div_name;
                        } ?>" class="form-control" placeholder="Name" maxlength="50">
                                             @if ($errors->has('div_name'))
                                    <div class="error_field" >{{ $errors->first('div_name') }}</div>
                                    @enderror
                                    </div>
                                    <!-- /.form-group -->
                                    <!-- /.form-group -->
                                </div>
                                <!-- /.col -->
                                <div class="col-md-6 left_pdng">
                                    <div class="form-group">
                                        <label>Code:</label>
                                        <input type="text" value="<?php if (isset($DataObj->div_code)) {
                            echo $DataObj->div_code;
                        } ?>"   class="form-control" id="div_code" name="div_code" placeholder="code" maxlength="20">
                                    </div>
                                    <!-- /.form-group -->
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="clearfix">
                                <div class="col-md-6 right_pdng">
                                    <div class="form-group">
                                        <label>Description:</label>
                                        <textarea id="div_desc"  id="div_desc" name="div_desc" class="form-control" placeholder="Description" maxlength="300"><?php if (isset($DataObj->div_code)) {
                            echo $DataObj->div_code;
                        } ?></textarea>
                                    </div>
                                </div>
                                <div class="col-md-6 left_pdng">
                                    <div class="form-group pt-45">
                                        <label>Status</label>
                                        <div class="icheck-primary d-inline">
                                            <input type="radio" id="In-Active"  name="div_status"<?php if (isset($DataObj->div_status) && $DataObj->div_status==0) { ?>checked=""<?php } ?> value="0" class="custom-control-input">
                                            <label for="In-Active">In-Active
                                            </label>
                                        </div>
                                        <div class="icheck-primary d-inline">
                                            <input type="radio"  <?php if (isset($DataObj->div_status) && $DataObj->div_status==1) { ?>checked=""<?php } ?>  id="Active" name="div_status" value="1"  class="custom-control-input">
                                            <label for="Active">Active
                                            </label>
                                        </div>
                                         @if ($errors->has('div_status'))
                                    <div class="error_field" >{{ $errors->first('div_status') }}</div>
                                    @enderror
                                    </div>
                                </div>
                            </div>
                            <div class="row" >
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-primary btn-submit">Submit</button>
                                
                            </div>
                            <div class="col-md-6 right">
                                <button type="button" class="btn btn-primary btn-submit" onclick="javascript:location.replace('{{ route('division.index') }}')">Back</button>
                            </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection

resources/views/division/index.blade.php
@extends('layouts.app')


@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Division List
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Home</a></li>
        <li class="active">Division List</li>
    </ol>
</section>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                <div class="col-sm-12 list_filter_head">
                    <div class="search_box">
                        <!-- search form -->
                        <form action="#" method="get" class="sidebar-form">
                            <div class="input-group">
                                <input type="text" name="searchtxt" value="<?php echo isset($data->searchtxt) ? $data->searchtxt : ''; ?>"  class="form-control search" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button type="submit" name="search" value="save" id="search-btn" class="btn btn-flat">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="userbtn">

                        <a href="{{ route('division.create') }}" class="btn btn-sm btn-primary createuser-btn">
                            <i class="fa fa-plus-circle"></i> Add Divisions
                        </a>
                    </div>
                </div>
            </div>

            <!-- /.card-header -->
            <div class="card-body">

                @if ($message = Session::get('success'))
                <div class="message" role="alert">
                    <div class="alert alert-success  alert-dismissible">
                  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <p>{{ $message }}</p>

                    </div>
                </div>
                @endif
                <div class="container-fluid p-0 show-enteries-parent">
                        <div class="col-md-6 p-0"><label class="show-enteries-text">Show enteries
                        <select id="item-show-per-page-select" class="item-show-per-page-select-id">
                        <option value="10">10</option>
                        <option value="50">50</option>
                        <option value="150">150</option>
                        <option value="500">500</option>
                        </select></label>

                        </div>
                        <div class="col-md-6 p-0">
                            <p class="showing-enteries-text text-right">Showing 1 to 10 of 57 entries</p>
                            

                        </div>
                        </div>

                <div class="table_data">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Code</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            <?php foreach ($data as $row) { ?>
                                </tr>
                            <td><?php echo $row->id ?></td>
                            <td><?php echo $row->div_name ?></td>
                            <td><?php echo $row->div_code ?></td>
                            <td><?php echo $row->div_desc ?></td>
                            <td><?php echo $row->div_status ? 'Active' : 'In-Active' ?></td>
                            <td>

                                <a class="btn btn-primary btn_dis" title="Edit" href="{{ route('division.edit',$row->id) }}"  data-toggle="tooltip" title="Edit!"><i class="fa fa-edit"></i></a>

                                {!! Form::open(['method' => 'DELETE','route' => ['division.destroy', $row->id],'style'=>'display:inline']) !!}


                                {!! Form::button('<i class="fa fa-archive"></i>', ['class' => 'btn btn-danger btn_dis', 'type'=>'submit', 'data-toggle'=>'tooltip', 'title'=>'Delete!']) !!}

                                {!! Form::close() !!}
                            </td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
            <div class="col-md-12 text-right pagination">
                {!! $data->render() !!}
            </div>
        </div>
</section>




@endsection